// AUTO-GENERATED by UraJS — edit your pages, not this file.
import Ura from "ura";
{{imports}}

Ura.setRoutes({
{{routes}}
});

Ura.setKeepAlive({
{{keepAlive}}
});

Ura.setStyles({{styles}});

Ura.start();
