// AUTO-GENERATED by UraJS — edit your pages, not this file.
import Ura from "ura";
import * as Blog from "./blog/page.js";
import * as BlogSlug from "./blog/[slug]/page.js";
import * as Conditions from "./conditions/page.js";
import * as Effects from "./effects/page.js";
import * as Home from "./home/page.js";
import * as Loops from "./loops/page.js";
import * as Search from "./search/page.js";
import * as State from "./state/page.js";
import * as State2 from "./state2/page.js";
import * as Svg from "./svg/page.js";
import * as Todos from "./todos/page.js";

Ura.setRoutes({
  "/": Home.default,
  "/blog": Blog.default,
  "/blog/:slug": BlogSlug.default,
  "/conditions": Conditions.default,
  "/effects": Effects.default,
  "/home": Home.default,
  "/loops": Loops.default,
  "/search": Search.default,
  "/state": State.default,
  "/state2": State2.default,
  "/svg": Svg.default,
  "/todos": Todos.default,
});

Ura.setKeepAlive({
  "/blog": Blog.keepAlive,
  "/blog/:slug": BlogSlug.keepAlive,
  "/conditions": Conditions.keepAlive,
  "/effects": Effects.keepAlive,
  "/home": Home.keepAlive,
  "/loops": Loops.keepAlive,
  "/search": Search.keepAlive,
  "/state": State.keepAlive,
  "/state2": State2.keepAlive,
  "/svg": Svg.keepAlive,
  "/todos": Todos.keepAlive,
});

Ura.setStyles([
  "/pages/main.css",
  "/layout.css"
]);

Ura.start();
